[module]
  [module.hugoVersion]
    extended = true
    min = '0.110.0'

[[menu.main]]
name = "Project Overview"
url = "#project-name-to-be-decided"
weight = 1

[[menu.main]]
name = "Research Sources"
url = "#research-sources"
weight = 2

[[menu.main]]
name = "Project Plan"
url = "#project-plan"
weight = 3

[[menu.main]]
name = "Social Media Strategy"
url = "#social-media-strategy"
weight = 4

[params]
showMenuItems = true
